### Dataset ###
data:
  name: custom
  folder: /Users/zhc/Documents/PhD/projects/TimeSeriesUnifiedModel/VerbalTSDatasets/synthetic_u
  data_path: /Users/zhc/Documents/PhD/projects/TimeSeriesUnifiedModel/VerbalTSDatasets/synthetic_u
  window_size: 128
  retinal_resize: [ 256, 337 ]

### Evaluate ###
eval:
  n_samples: 10
  model_path: ""
  batch_size: 128
  display_interval: 1
  device: cuda:0

  cache_folder: ./cache/synth-m_text
